import { findSample, type Sample } from '../samples'
import type { PlanRequest } from '../lib/types'
import raw from './fixture.json'

/**
 * The finished example.
 *
 * AskSheet is an odd product to build a demo for, because the expensive half is
 * invisible. The data never leaves the browser, the bundled CSV is already in the
 * bundle, and DuckDB runs on the visitor's machine — all of that is instant and
 * free. The only thing that costs a round trip and a quota unit is *planning* the
 * query, and that is the only thing worth pre-recording.
 *
 * So the fixture holds plans, not answers: for each question, the SQL the
 * deployed planner wrote, the sentence it wrote, and the Vega-Lite spec if it
 * emitted one. Clicking a question runs that SQL against the real sample in
 * DuckDB, here and now. The numbers on screen are computed on the visitor's
 * machine at the moment they look at them; only the planning step is replayed.
 *
 * That is a distinction worth being pedantic about, and the UI says it out loud
 * on every answer rather than quietly implying the whole thing is canned.
 *
 * `fixture.json` is generated by `scripts/capture-example.mjs`, which drives the
 * app's own `ask()` loop against the deployed Edge Function with a profile built
 * from a genuine DuckDB load of the bundled CSV. Nothing in it is hand-written;
 * see the header of that script.
 */

export interface ExamplePlan {
  question: string
  /** Index of the question this one followed up on, or null if it stands alone. */
  follows: number | null
  /** The exact body posted to `asksheet-plan` to obtain the SQL below. */
  request: PlanRequest
  requestBytes: number
  sql: string
  narration: string
  chart: Record<string, unknown> | null
  /** True when the planner's first statement failed at capture time and this is
   *  the corrected one. A property of the recording, not of this run. */
  repaired: boolean
  /** Shape seen when the SQL was captured. Never rendered — it exists so
   *  `example.test.ts` can catch a fixture that has drifted from the sample. */
  observed: { columns: string[]; rowCount: number }
}

export interface ExampleFixture {
  /** Bumped when this module can no longer read an older file, so a stale
   *  fixture fails a test rather than half-rendering. */
  schema: number
  generatedBy: string
  capturedAt: string
  endpoint: string
  sampleId: string
  table: string
  strict: boolean
  plans: ExamplePlan[]
}

/**
 * `as unknown as` rather than a structural check at import time.
 *
 * The file is generated, so a mismatch is a build-time mistake rather than
 * untrusted input, and paying a validation pass on every page load to guard
 * against our own script would be theatre. `example.test.ts` asserts the shape
 * instead, where a failure costs a red test rather than a broken tab.
 */
export const EXAMPLE = raw as unknown as ExampleFixture

/** The bundled dataset the plans were captured against. */
export function exampleSample(): Sample {
  const sample = findSample(EXAMPLE.sampleId)
  if (!sample) {
    throw new Error(
      `The example fixture was captured against a sample called "${EXAMPLE.sampleId}", ` +
        'which is no longer bundled. Regenerate it: npm run capture:example -w apps/asksheet.',
    )
  }
  return sample
}

/**
 * The questions that must run before this one, oldest first.
 *
 * A follow-up was planned with its predecessor's SQL in `history`, so showing it
 * on its own would present a conversation with the first half missing. Clicking
 * it replays the chain.
 */
export function prerequisites(index: number): number[] {
  const chain: number[] = []
  let cursor = EXAMPLE.plans[index]?.follows ?? null
  while (cursor !== null && !chain.includes(cursor)) {
    chain.unshift(cursor)
    cursor = EXAMPLE.plans[cursor]?.follows ?? null
  }
  return chain
}

/** "7 August 2026" — the date on the saved plan, for the label that distinguishes
 *  it from the computation happening now. */
export function capturedOn(iso: string = EXAMPLE.capturedAt): string {
  const when = new Date(iso)
  if (Number.isNaN(when.getTime())) return 'an earlier date'
  return when.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
}

/** What a replayed answer needs in order to describe its own provenance. */
export interface ReplayProvenance {
  capturedAt: string
  requestBytes: number
  request: PlanRequest
  repaired: boolean
  /** The question this one followed up on, if any. */
  followsQuestion: string | null
}

export function provenanceOf(plan: ExamplePlan): ReplayProvenance {
  const follows = plan.follows === null ? null : (EXAMPLE.plans[plan.follows]?.question ?? null)
  return {
    capturedAt: EXAMPLE.capturedAt,
    requestBytes: plan.requestBytes,
    request: plan.request,
    repaired: plan.repaired,
    followsQuestion: follows,
  }
}
